### ISSUE TITLE
Extract all kind of customization in a plugin

### ISSUE THREAD

**Issue by mitogh** [moxienyc/some-like-it-neat#2]
Try to extract as much as possible in a Plugin, so the theme should focus only in display content and nothing else. 

Behavior and logic should be handled by plugins and in this case because most of the logic it's common we can create a Moxie Plugin to use in all our projects.

Any comment about this please let me know.

@jeffreynolte @wissambellali @nacho87 @desaiuditd

**Comment by jeffreynolte** [comment]
@mitogh - Totally agree with you on this, more of a MVC approach to WordPress. similar to how we have been handling in our themes. What is your suggestions for implementation?

**Comment by mitogh** [comment]
@jeffreynolte I was thinking in having a Moxie Plugin with some common behavior in different projects like common functions and hooks used in all projects so we can delegate of logic from theme to this plugin as well using the Glue plugin is another way to separate Model form the view so this theme should behave as the View.

**Comment by jeffreynolte** [comment]
@mitogh - Do you know of any plugins that exist in this way currently? I would like to explore if there are any other shops taking an MVC approach in this way.

**Comment by mitogh** [comment]
Well I did some small research on this but I haven't worked with something like that in WP, i see big companies like www.studiopress.com/‎ create starter themes so the developer or owner creates a child theme based on your themes, but I think this approach it's the same as other than have all the data and logic in the theme I think the theme should only be to display data and not no handle internal and logic components of WP.

For example, things like: enable svg, custom menus on top of Walker class of WP, I think should be handled outside of the theme and because things like that are supposed to be there even if we change the theme also this behaviours are common in most other projects, so what I was thinking is have the following structure:

- Moxie Plugin (Handles common behaviours in all projects)
- Project Plugin (Handles the specific logic of the theme).
- Glue Plugin (Handles the link between the data and layout)
- Theme (Handles the layout).

**Comment by jeffreynolte** [comment]
@mitogh - This makes sense, I guess the only piece that is a bit confusing is the Moxie Plugin piece.  How should we begin to break this out? should we open a repo and define a list of common behavior across all recent projects?

Thoughts?

cc: @desaiuditd @mitogh

**Comment by mitogh** [comment]
Well that sounds good for me, we can start by developing a custom version of the customizer including in the moxie logo and some basic features, as well and more easy way to add options to customise, things like: 

- add/remove trackduck.

Other options: 

- add support for SVG.
- add styles for SVG in the admin for ACF.

Other methods.
- generate responsive images passing only an image ID.
- retrieve an image url passing an image ID and size.
- generate a background style image passing only image ID and size.

cc @jeffreynolte @desaiuditd

**Comment by jeffreynolte** [comment]
Great! @mitogh I can open a repo for this. Want to just call it "moxie"?

**Comment by mitogh** [comment]
I'm closing this one this customisations are being done on the Moxie plugin.
